# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param a a param of beta distribution
#' @param b another param of beta distribution
#' @param n sample size
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,2,3,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, a, b, n) {
    .Call('_SA23204168_gibbsC', PACKAGE = 'SA23204168', N, a, b, n)
}

#' @title Compute the maximum l2 norm for each column of the matrix
#' @description Compute the maximum l2 norm for each column of the matrix
#' @param x the object matrix
#' @return the maximum l2 norm for each column of the matrix
#' @examples
#' \dontrun{
#' x <- matrix(c(1, 2, 4, 9), 2, 2)
#' print(lmax(x))
#' }
#' @export
lmax <- function(x) {
    .Call('_SA23204168_lmax', PACKAGE = 'SA23204168', x)
}

